In [13]:
import numpy as np
A = np.array([ 7, 8, 6, 7, 8, 6, 3, 6])
print(A)

sum_a = np.sum(A)
print(sum_a)

B = np.array([42, 7, 7, 7, 14, 14, 7, 7])
print(B)


C = A/B
print(C)

D = np.array([36, 13, 10, 10, 15, 10, 4, 7])
print(D)

E = D * C
print(E)

sum_e = np.sum(E)
print(sum_e)



[7 8 6 7 8 6 3 6]
51
[42  7  7  7 14 14  7  7]
[0.16666667 1.14285714 0.85714286 1.         0.57142857 0.42857143
 0.42857143 0.85714286]
[36 13 10 10 15 10  4  7]
[ 6.         14.85714286  8.57142857 10.          8.57142857  4.28571429
  1.71428571  6.        ]
60.0
