In [1]:
# creating vector A: "Assessment"

import numpy as np
A = np.array([ 7, 8, 6, 7, 8, 6, 3, 6])
print(A)

[7 8 6 7 8 6 3 6]


In [3]:
# calculating the sum of the elements of vector A: "happiness indicator."

sum_a = np.sum(A)
print(sum_a)

51


In [12]:
# creating a vector B: "The metrics of my life distribution across different spheres"

B = np.array([42, 7, 7, 7, 14, 14, 7, 7])
print(B)

[42  7  7  7 14 14  7  7]


In [5]:
# calculating vector C: "My life efficiency"

C = A/B
print(C)

[0.16666667 1.14285714 0.85714286 1.         0.57142857 0.42857143
 0.42857143 0.85714286]


In [13]:
# creating vector D: "Redistributed number of hours"

D = np.array([36, 13, 10, 10, 15, 10, 4, 7])
print(D)

[36 13 10 10 15 10  4  7]


In [7]:
# calculating vector E: "my forecasted satisfaction with the respective life spheres."

E = D * C
print(E)


[ 6.         14.85714286  8.57142857 10.          8.57142857  4.28571429
  1.71428571  6.        ]


In [8]:
# calculating the sum of the elements of vector E: "my the forecasted happiness indicator"

sum_e = np.sum(E)
print(sum_e)

60.0
